version: '3.9'
services:
  app:
    container_name: go-api
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      DATABASE_HOST: ${DB_HOST}
      DATABASE_PORT: ${DB_PORT}
      TEST_POSTGRES_USER: ${TEST_DB_USER}
      TEST_POSTGRES_PASSWORD: ${TEST_DB_PASSWORD}
      TEST_POSTGRES_DB: ${TEST_DB_NAME}
      TEST_DATABASE_HOST: ${TEST_DB_HOST}
      TEST_DATABASE_PORT: ${TEST_DB_PORT}
    tty: true
    build: .
    ports:
      - 8000:8080
    # volumes:
    #   - .:/app
    depends_on:
      postgresdb:
        condition: service_healthy
        restart: true
    networks:
      - developing

  postgresdb:
    container_name: postgres_container
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      # DATABASE_HOST: ${DB_HOST}
    healthcheck:
      test: pg_isready -U ${DB_USER} -d ${DB_NAME}
      interval: 1s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: always
    ports:
      - '5432:5432'
    networks:
      - developing

  postgresdb_test:
    container_name: postgres_test_container
    image: postgres:latest
    environment:
      POSTGRES_USER: ${TEST_DB_USER}
      POSTGRES_PASSWORD: ${TEST_DB_PASSWORD}
      POSTGRES_DB: ${TEST_DB_NAME}
      # DATABASE_HOST: ${TEST_DB_HOST}
    ports:
      - '5433:5432'
    networks:
      - developing

  pgadmin-golang-container:
    container_name: pgadmin-golang-container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_WTF_CSRF_ENABLED: "False"
    ports:
      - "8888:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      postgresdb:
        condition: service_healthy
    networks:
      - developing

# Networks to be created to facilitate communication between containers
networks:
  developing:
    driver: bridge

volumes:
  pgadmin-data: