name: Go API CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Build Docker image
      run: docker-compose build

    - name: Run tests in Docker Compose
      run: docker-compose run app go test ./... -v

    - name: Lint the Dockerfile
      run: docker run --rm -i hadolint/hadolint < Dockerfile

    - name: Run docker-compose up
      run: docker-compose up -d

    - name: Run tests
      run: docker-compose exec app go test ./... -v

    - name: Tear down Docker Compose
      run: docker-compose down
